### ISSUE TITLE
Invalid LiteCoin EXT_PUBLIC_KEY and EXT_PRIVATE_KEY

### ISSUE THREAD

**Issue by aaska** [MetacoSA/NBitcoin.Litecoin#5]
Hello,

I was struggling trying to derive Ltub key to L/M keys when parsing the content in ExtPubKey.Parse. After some research, I was able to perform the operation but I had to change in the Network Initializers the two following lines :

	.SetBase58Bytes(Base58Type.EXT_PUBLIC_KEY, new byte[] { 0x01, 0x9D, 0xA4, 0x62 })
	.SetBase58Bytes(Base58Type.EXT_SECRET_KEY, new byte[] { 0x01, 0x9D, 0x9C, 0xFE })

and then I was able to achieve my key derivations.

I found this list on a forum which seems to come from the pycoin api :

EXT_SECRET_KEY, EXT_PUBLIC_KEY # Network                 : Prefixes
0x0488ADE4,     0x0488B21E     # BTC  Bitcoin    mainnet : xprv / xpub
0x04358394,     0x043587CF     # BTC  Bitcoin    testnet : tprv / tpub
0x019D9CFE,     0x019DA462     # LTC  Litecoin   mainnet : Ltpv / Ltub
0x0436EF7D,     0x0436F6E1     # LTC  Litecoin   testnet : ttpv / ttub
0x02FE52F8,     0x02FE52CC     # DRK  Darkcoin   mainnet : drkv / drkp
0x3A8061A0,     0x3A805837     # DRK  Darkcoin   testnet : DRKV / DRKP
0x0488ADE4,     0x0488B21E     # VIA  Viacoin    mainnet : xprv / xpub
0x04358394,     0x043587CF     # VIA  Viacoin    testnet : tprv / tpub
0x02FD3955,     0x02FD3929     # DOGE Dogecoin   mainnet : dogv / dogp
0x0488ADE4,     0x0488B21E     # VTC  Vertcoin   mainnet : vtcv / vtcp
0x02CFBF60,     0x02CFBEDE     # BC   Blackcoin  mainnet : bcpv / bcpb
0x03A04DB7,     0x03A04D8B     # MEC  Megacoin   mainnet : mecv / mecp
0x0488ADE4,     0x0488B21E     # MYR  Myriadcoin mainnet : myrv / myrp
0x0488ADE4,     0x0488B21E     # UNO  Unobtanium mainnet : unov / unop
0x037A6460,     0x037A689A     # JBS  Jumbucks   mainnet : jprv / jpub
0x0488ADE4,     0x0488B21E     # MZC  Mazacoin   mainnet : xprv / xpub

**Comment by NicolasDorier** [comment]
ah? This is strange I remember taking this data out of the Litecoin source code. What is a typo ?

**Comment by aaska** [comment]
I think it is a typo as the currently defined EXT_PUBLIC_KEY and EXT_PRIVATE_KEY matches those of the bitcoin network instead of the Litecoin Network

**Comment by NicolasDorier** [comment]
@aaska it seems that this is not what litecoin is using https://github.com/litecoin-project/litecoin/blob/master/src/chainparams.cpp#L137

**Comment by aaska** [comment]
Indeed, I'm sorry, after some research some software are pulling Ltub and Ltpv instead of the xpub and xprv.. Though it's now an easy fix to eventually handle both conditions !

Thank you!

**Comment by clarkmoody** [comment]
I've started assembling a [registry of HD version bytes](https://github.com/satoshilabs/slips/blob/master/slip-0132.md) if anyone feels like contributing :-)

**Comment by NicolasDorier** [comment]
@clarkmoody it is very useful. If you can make a test vector it would just be perfect.

**Comment by clarkmoody** [comment]
@NicolasDorier I've added those test vectors in a [PR to the SLIP](https://github.com/satoshilabs/slips/pull/198). They are Bitcoin-only at this point, just to get something up there quickly.
